gText_Birch_Welcome::
	.string "Ah, good. The camera is working.\p"
	.string "Greetings.\p"
	.string "My name is Professor Amanita.\n"
	.string "Though I'm sure you already know that.\p"
	.string "Now…\p"
	.string "On with business.\p"
	.string "You wished to assist with my work in\n"
	.string "Pokémon research, correct?\p"
	.string "$"

gText_Birch_Pokemon::
	.string "As a researcher, you will be given a\n"
	.string "partner Pokémon like so to assist with\l"
	.string "field work.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Though, I certainly would not entrust a\n"
	.string "newcomer with a Pokémon as fickle as\l"
	.string "Amewba.\p"
	.string "No- you will be given a choice of three\n"
	.string "partner Pokémon to select from.\p"
	.string "I'm sure that sounds quite exciting to a\n"
	.string "new trainer such as yourself, does\l"
	.string "it not?\p"
	.string "Exploring the far reaches of the Gagil\n"
	.string "region, bonding with your very own\l"
	.string "partner Pokémon…\p"
	.string "Potentially even training up a full team\n"
	.string "to battle with others.\p"
	.string "Ah, young ambition… such a quaint thing.\p"
	.string "Now, I do apologize for this…\p"
	.string "I'm certain you've already filled out\n"
	.string "this information in the application\l"
	.string "form, but for formality's sake, I'll need\l"
	.string "you to re-enter your information.\p"
	.string "I know, I know.\p"
	.string "It's a hassle for me as well.\p"
	.string "Unfortunately, that is simply the nature\n"
	.string "of our application system.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "I've sent you the link to this form over\n"
	.string "the call's text chat.\p"
	.string "Now…$"

gText_Birch_BoyOrGirl::
	.string "Please enter your gender\n"
	.string "in the first text box.$"

gText_Birch_WhatsYourName::
	.string "Alright. Now, please enter your name in\n"
	.string "the next text box.$"

gText_Birch_SoItsPlayer::
	.string "Is {PLAYER} correct?$"

gText_Birch_YourePlayer::
	.string "Wonderful.\p"
	.string "Yes, that name certainly sounds\n"
	.string "familiar…\p"
	.string "I believe I've heard my niece talk about\n"
	.string "you before.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}, it was a pleasure to meet you.\p"
	.string "I am sure you will make a phenomenal\n"
	.string "research assistant.\p"
	.string "I will be sending my son by later this\n"
	.string "week to bring you over to the field lab.\p"
	.string "Until then, take care.\p"
	.string "I and everyone else at Evo Co. hope to\n"
	.string "see you soon.\p"
	.string "$"
